import fs from 'fs';
import path from 'path';
import Head from 'next/head';

export default function Home({ posts }) {
    console.log(posts);
    return (
        <div>
            <Head>
                <title>My Blog</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <h2>Hello there</h2>
        </div>

    );
}

//fetch data //run as server side 
export async function getStaticProps() {

    const files = fs.readdirSync(path.join('posts'));

    console.log(files);

    return {
        props: {
            posts: 'Postings'
        }
    };
}